# Generated by Django 4.2 on 2025-04-15 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Укажите название объявления', max_length=256, verbose_name='Название объявления')),
                ('descriptions', models.TextField(help_text='Укажите описание', verbose_name='Описание')),
                ('created_at', models.DateField(default=django.utils.timezone.now, help_text='Время создания объявления', verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Укажите название категории', max_length=256, verbose_name='Название категории')),
                ('descriptions', models.TextField(help_text='Укажите описание', verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Укажите уникальный slug', unique=True, verbose_name='Cлаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Укажите название состояния', max_length=256, verbose_name='Название состояния')),
                ('descriptions', models.TextField(help_text='Укажите описание', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Напишите комментарий к предложению', verbose_name='комментарий')),
                ('status', models.TextField(choices=[('awaiting', 'Ожидает'), ('accepted', 'Принята'), ('cancelled', 'Отклонена')], default='awaiting', error_messages={'choices': 'Выберите правильный статус'}, help_text='Укажите статус', max_length=20, verbose_name='Статус предложения')),
                ('created_at', models.DateField(default=django.utils.timezone.now, help_text='Время создания предложения', verbose_name='Дата и время создания')),
                ('ad_receiver', models.ForeignKey(help_text='Укажите получателя', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('ad_sender', models.ForeignKey(help_text='Укажите объявление', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='ads.ad', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Предложние',
                'verbose_name_plural': 'Предложения',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(help_text='Укажите категорию', on_delete=django.db.models.deletion.CASCADE, to='ads.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.ForeignKey(help_text='Укажите состояние', on_delete=django.db.models.deletion.CASCADE, to='ads.condition', verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(help_text='Укажите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='exchangeproposal',
            constraint=models.UniqueConstraint(fields=('ad_sender', 'ad_receiver'), name='unique_ad_per_receiver'),
        ),
    ]
