# Generated by Django 4.2 on 2025-04-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Время создания объявления', verbose_name='Дата и время создания'),
        ),
    ]
