# Generated by Django 4.2 on 2025-04-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeproposal',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Время создания предложения', verbose_name='Дата и время создания'),
        ),
    ]
